In [1]:
import numpy as np

In [3]:
list_ = [ '1', '2' , '3' , '4' , '5' ]

In [7]:
array_list = np.array(object = list_)

In [6]:
#Ans 1)
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

type(list_) is a list whereas type(array_list) is an array.

In [9]:
#Ans2)
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
array_list.dtype

dtype('<U1')

In [14]:
for x in array_list:
    print(type(x))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [16]:
#Ans 3)
arr_list = np.array(object = list_, dtype = int)

In [17]:
arr_list

array([1, 2, 3, 4, 5])

In [18]:
for x in arr_list:
    print(type(x))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


There is a difference in datatype of list_ and arr_list as we can see the datatype of list_ ais string whereas arr_list have int64 as datatype.

In [26]:
# Ans 4) 
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [27]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [28]:
num_array = np.array(object = num_list)

In [29]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
num_array.shape

(2, 3)

In [31]:
num_array.size

6

In [38]:
# Ans 5)
new_array= np.zeros([3,3])

In [39]:
new_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
new_array.shape

(3, 3)

In [41]:
new_array.size

9

In [43]:
#Ans 6)
identity_matrix = np.eye(5,5)

In [44]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])